version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.txt  # Ensure this points to the correct Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_USER=latte
      - DB_PASSWORD=latte
      - DB_NAME=frappuccino
      - DB_PORT=5432
      - DATABASE_URL=postgres://latte:latte@db:5432/frappuccino?sslmode=disable
    depends_on:
      - db
    # Ensure entrypoint is set correctly to use wait-for-it.sh
    entrypoint: ["/wait-for-it.sh", "db:5432", "--timeout=30", "--", "./main"]

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=latte
      - POSTGRES_PASSWORD=latte
      - POSTGRES_DB=frappuccino
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
