version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_USER=latte
      - DB_PASSWORD=latte
      - DB_NAME=frappuccino
      - DB_PORT=5432
      - DATABASE_URL=postgres://latte:latte@db:5432/frappuccino?sslmode=disable
    depends_on:
      db:
        condition: service_healthy


  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=latte
      - POSTGRES_PASSWORD=latte
      - POSTGRES_DB=frappuccino
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U latte -d frappuccino"]
      interval: 5s
      timeout: 5s
      retries: 5
